/*
 * COURSE-C2-P1-01 — The text `kv-cache` draws (llm-agents Block 1 lesson 5, «La caché de
 * claves y valores»). GENERATED by scripts/courses/llm-agents/kv-cache-presets.py from the
 * mini-GPT checkpoint: after «La Nela», top-p with p = 0.9 and seed 0 until the context window
 * is full, 64 tokens — what the lesson's first cell generates with the cache. Do not edit by
 * hand; re-run the script.
 *
 * Each entry is [id, text]; a token that is not text on its own would be its bytes in hex.
 * math/__tests__/kv-cache.test.ts re-decodes every label from bpe-merges.json. Spanish-bound
 * like the checkpoint (corpora.ts, SPANISH_BOUND_CORPORA).
 */

/** How many of the tokens are the prompt, read in one pass before the first sample. */
export const KV_PROMPT_TOKENS = 2;

export const KV_TOKENS: readonly (readonly [number, string])[] = [
  [461, "La"],
  [373, " Nela"],
  [309, " no"],
  [276, " t"],
  [266, "ra"],
  [102, "f"],
  [293, "á"],
  [385, " como"],
  [330, " me"],
  [343, " di"],
  [353, "jo"],
  [356, " lo"],
  [384, " le"],
  [32, " "],
  [353, "jo"],
  [46, "."],
  [387, " D"],
  [101, "e"],
  [323, "ch"],
  [270, "as"],
  [101, "e"],
  [278, " que"],
  [100, "d"],
  [285, "ar"],
  [375, " más"],
  [314, " est"],
  [274, "re"],
  [108, "l"],
  [270, "as"],
  [481, " ent"],
  [274, "re"],
  [335, " las"],
  [439, " per"],
  [115, "s"],
  [279, "on"],
  [270, "as"],
  [260, " de"],
  [280, " la"],
  [317, " al"],
  [359, "ma"],
  [428, "das"],
  [260, " de"],
  [308, " su"],
  [263, " c"],
  [310, "al"],
  [108, "l"],
  [285, "ar"],
  [418, "se"],
  [46, "."],
  [376, " S"],
  [101, "e"],
  [330, " me"],
  [363, " in"],
  [103, "g"],
  [268, "en"],
  [101, "e"],
  [266, "ra"],
  [114, "r"],
  [305, " se"],
  [342, " ha"],
  [260, " de"],
  [99, "c"],
  [304, "ía"],
  [261, " s"],
];
