/*
 * REFACTOR-R4-P2-02 — Build the Material Symbols SUBSET font (`pnpm build:icons`).
 *
 * The self-hosted icon font used to be the full variable font: 3.9 MB, ~3,800 glyphs,
 * four axes, preloaded with `display: "block"` on every page. The app uses ~100 icons,
 * one weight, one optical size, and toggles only `FILL`. This script downloads a subset
 * of exactly `ICON_NAMES` (`src/constants/icons.ts`) from the Google Fonts CSS API:
 *   - `icon_names=` keeps only those glyphs (the API wants the list sorted),
 *   - `opsz 24 / wght 400 / GRAD 0` are pinned (what globals.css used to fix at runtime),
 *   - `FILL 0..1` stays a variable axis (pressed thumbs, rating stars, progress card).
 *
 * It writes the woff2 that `next/font/local` loads in `src/app/[locale]/layout.tsx`, and
 * a manifest beside it (the names + the woff2's sha256) so `pnpm check:icons` can tell
 * when `ICON_NAMES` changed without the font being rebuilt. Commit both files; the woff2
 * is a build artifact of `ICON_NAMES` — never hand-edit it.
 *
 * Needs network. Uses `console` deliberately (plain CLI, like `check-messages.ts`).
 */

import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";

import { ICON_NAMES } from "@/constants/icons";
import { ICON_FONT_FILE, ICON_MANIFEST_FILE, type IconFontManifest } from "@/lib/icons/check-icons";

const FONT_PATH = path.join(process.cwd(), ICON_FONT_FILE);
const MANIFEST_PATH = path.join(process.cwd(), ICON_MANIFEST_FILE);

// Google serves TTF to user agents it doesn't recognise as woff2-capable.
const MODERN_UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36";

const AXES = "opsz,wght,FILL,GRAD@24,400,0..1,0";

async function main() {
  const names = [...ICON_NAMES].sort();
  const cssUrl =
    `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:${AXES}` +
    `&icon_names=${names.join(",")}&display=block`;

  const cssRes = await fetch(cssUrl, { headers: { "user-agent": MODERN_UA } });
  if (!cssRes.ok) throw new Error(`Google Fonts CSS: HTTP ${cssRes.status}\n${await cssRes.text()}`);
  const css = await cssRes.text();

  const woff2Url = /src:\s*url\(([^)]+)\)\s*format\(['"]woff2['"]\)/.exec(css)?.[1];
  if (!woff2Url) throw new Error(`No woff2 url in the Google Fonts CSS:\n${css}`);

  const fontRes = await fetch(woff2Url, { headers: { "user-agent": MODERN_UA } });
  if (!fontRes.ok) throw new Error(`woff2 download: HTTP ${fontRes.status}`);
  const font = Buffer.from(await fontRes.arrayBuffer());
  if (font.subarray(0, 4).toString("latin1") !== "wOF2") {
    throw new Error("The downloaded file is not a woff2 (bad magic).");
  }

  fs.writeFileSync(FONT_PATH, font);
  const manifest: IconFontManifest = {
    note: "Generated by `pnpm build:icons` (scripts/icons/build-icon-font.ts). Do not edit.",
    axes: AXES,
    sha256: createHash("sha256").update(font).digest("hex"),
    names,
  };
  fs.writeFileSync(MANIFEST_PATH, `${JSON.stringify(manifest, null, 2)}\n`);

  console.log(
    `✓ ${path.relative(process.cwd(), FONT_PATH)}: ${names.length} icons, ${font.length.toLocaleString("en")} bytes`,
  );
}

main().catch((err) => {
  console.error(`✗ build:icons failed: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
