"""COURSE-C2-P1-01 — Congela el texto que dibuja el explorable `kv-cache`.

    python kv-cache-presets.py [--salida RUTA]

Carga el checkpoint como lo cargan las celdas (minigpt.py, bpe.py, bpe-merges.json y
minigpt.json de public/courses/llm-agents/) y genera lo mismo que la primera celda de la
leccion 1·5 («La cache de claves y valores»): tras «La Nela», top-p con p = 0.9 y la semilla
0, hasta llenar la ventana de contexto, 64 tokens. La celda genera con la cache y comprueba,
posicion a posicion, que los logits son los de `adelante` sobre el texto entero; aqui basta
`generar`, que es la segunda manera y da los mismos tokens.

Escribe src/features/courses/widgets/math/kv-cache-presets.ts: los ids y el texto de cada
token, que el explorable pinta uno por posicion mientras la cache crece. Un token que no es
texto por si solo (un byte suelto de un caracter de dos) se escribe como sus bytes en
hexadecimal, como en `bpe-merges`; math/__tests__/kv-cache.test.ts vuelve a decodificar cada
etiqueta desde bpe-merges.json.

Como train-minigpt.py, no corre en CI: su salida esta en el repositorio.
"""
import os

for var in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ[var] = "1"

import argparse
import importlib.util
import json

import numpy as np

AQUI = os.path.dirname(os.path.abspath(__file__))
RAIZ = os.path.abspath(os.path.join(AQUI, "..", "..", ".."))
ASSETS = os.path.join(RAIZ, "public", "courses", "llm-agents")
SALIDA = os.path.join(RAIZ, "src", "features", "courses", "widgets", "math", "kv-cache-presets.ts")

PROMPT = "La Nela"
T_CTX = 64
TOP_P = 0.9
SEMILLA = 0


def importar(nombre):
    spec = importlib.util.spec_from_file_location(nombre, os.path.join(ASSETS, nombre + ".py"))
    modulo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(modulo)
    return modulo


def etiqueta(b):
    """El texto del token, o sus bytes en hexadecimal si no es UTF-8 valido por si solo."""
    try:
        return b.decode("utf-8")
    except UnicodeDecodeError:
        return " ".join("%02X" % x for x in b)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--salida", default=SALIDA)
    args = ap.parse_args()
    bpe, mg = importar("bpe"), importar("minigpt")
    with open(os.path.join(ASSETS, "bpe-merges.json"), encoding="utf-8") as f:
        fusiones = [tuple(p) for p in json.load(f)]
    vocab = bpe.vocabulario(fusiones)
    with open(os.path.join(ASSETS, "minigpt.json"), encoding="utf-8") as f:
        modelo = mg.MiniGPT.cargar(f.read())

    prompt = bpe.codificar(PROMPT, fusiones)
    ids = modelo.generar(prompt, T_CTX - len(prompt), top_p=TOP_P, rng=np.random.default_rng(SEMILLA))
    print(repr(bpe.decodificar(ids, fusiones)))
    filas = ["  [%d, %s]," % (i, json.dumps(etiqueta(vocab[i]), ensure_ascii=False)) for i in ids]

    ts = (
        "/*\n"
        " * COURSE-C2-P1-01 — The text `kv-cache` draws (llm-agents Block 1 lesson 5, «La caché de\n"
        " * claves y valores»). GENERATED by scripts/courses/llm-agents/kv-cache-presets.py from the\n"
        " * mini-GPT checkpoint: after «%s», top-p with p = %s and seed %d until the context window\n"
        " * is full, %d tokens — what the lesson's first cell generates with the cache. Do not edit by\n"
        " * hand; re-run the script.\n"
        " *\n"
        " * Each entry is [id, text]; a token that is not text on its own would be its bytes in hex.\n"
        " * math/__tests__/kv-cache.test.ts re-decodes every label from bpe-merges.json. Spanish-bound\n"
        " * like the checkpoint (corpora.ts, SPANISH_BOUND_CORPORA).\n"
        " */\n\n"
        "/** How many of the tokens are the prompt, read in one pass before the first sample. */\n"
        "export const KV_PROMPT_TOKENS = %d;\n\n"
        "export const KV_TOKENS: readonly (readonly [number, string])[] = [\n%s\n];\n"
    ) % (PROMPT, TOP_P, SEMILLA, T_CTX, len(prompt), "\n".join(filas))
    with open(args.salida, "w", encoding="utf-8") as f:
        f.write(ts)
    print("escrito", os.path.relpath(args.salida, RAIZ))


if __name__ == "__main__":
    main()
