"""COURSE-C2-P1-01 — Congela los dos vectores de logits del explorable `sampling-explorer`.

    python sampling-presets.py [--salida RUTA]

Carga el checkpoint como lo cargan las celdas (minigpt.py, bpe.py, bpe-merges.json y
minigpt.json de public/courses/llm-agents/), pasa cada contexto por `adelante` y escribe
src/features/courses/widgets/math/sampling-presets.ts: los 512 logits de la ULTIMA posicion,
redondeados a 4 decimales como los pesos, y el texto de las entradas mas probables, que son
las que el explorable dibuja una por una.

Los dos contextos son la leccion 1·4 («Muestreo»): uno abierto, donde el modelo reparte su
apuesta entre muchas entradas, y uno casi decidido, donde una sola se lleva casi toda la
masa. Juntos ensenan lo que top-k no ve y top-p si: cuantas entradas hacen falta depende del
contexto. La primera celda de la leccion imprime, desde Pyodide, los numeros de estos mismos
vectores, y math/__tests__/sampling.test.ts los aserta contra el fichero que escribe esto.

Como train-minigpt.py, no corre en CI: su salida esta en el repositorio.
"""
import os

for var in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ[var] = "1"

import argparse
import importlib.util
import json

import numpy as np

AQUI = os.path.dirname(os.path.abspath(__file__))
RAIZ = os.path.abspath(os.path.join(AQUI, "..", "..", ".."))
ASSETS = os.path.join(RAIZ, "public", "courses", "llm-agents")
SALIDA = os.path.join(RAIZ, "src", "features", "courses", "widgets", "math", "sampling-presets.ts")

# id del preset (clave de estado, invariante de idioma) -> contexto
CONTEXTOS = [("open", "La Nela"), ("peaked", "La Nela bajó la cabe")]
N_ETIQUETAS = 12                                 # las filas que el explorable dibuja
DECIMALES = 4


def envolver(trozos, sangria):
    """Une `trozos` con ", " en lineas de menos de 100 columnas, con la sangria dada."""
    lineas, linea = [], sangria
    for trozo in trozos:
        if len(linea) + len(trozo) > 98:
            lineas.append(linea.rstrip())
            linea = sangria
        linea += trozo + ", "
    lineas.append(linea.rstrip())
    return "\n".join(lineas)


def importar(nombre):
    spec = importlib.util.spec_from_file_location(nombre, os.path.join(ASSETS, nombre + ".py"))
    modulo = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(modulo)
    return modulo


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--salida", default=SALIDA)
    args = ap.parse_args()
    bpe, mg = importar("bpe"), importar("minigpt")
    with open(os.path.join(ASSETS, "bpe-merges.json"), encoding="utf-8") as f:
        fusiones = [tuple(p) for p in json.load(f)]
    vocab = bpe.vocabulario(fusiones)
    with open(os.path.join(ASSETS, "minigpt.json"), encoding="utf-8") as f:
        modelo = mg.MiniGPT.cargar(f.read())

    bloques = []
    for clave, contexto in CONTEXTOS:
        ids = bpe.codificar(contexto, fusiones)
        z = modelo.adelante(np.array([ids]))[0][0, -1]
        z = np.round(z, DECIMALES) + 0.0
        q = mg.softmax(z)
        orden = np.argsort(-q, kind="stable")[:N_ETIQUETAS]
        etiquetas = {int(i): vocab[i].decode("utf-8") for i in orden}
        print("%-8s %r: %s" % (clave, contexto, [(etiquetas[int(i)], round(float(q[i]), 3)) for i in orden[:5]]))
        bloques.append(
            "  {\n"
            '    id: "%s",\n'
            "    context: %s,\n"
            "    labels: {\n%s\n    },\n"
            "    logits: [\n%s\n    ],\n"
            "  }," % (
                clave,
                json.dumps(contexto, ensure_ascii=False),
                envolver(["%d: %s" % (i, json.dumps(t, ensure_ascii=False)) for i, t in etiquetas.items()], "      "),
                envolver(["%.4f" % v for v in z], "      "),
            )
        )

    ts = (
        "/*\n"
        " * COURSE-C2-P1-01 — The frozen logit vectors of `sampling-explorer` (llm-agents Block 1\n"
        " * lesson 4, «Muestreo»). GENERATED by scripts/courses/llm-agents/sampling-presets.py from\n"
        " * the mini-GPT checkpoint (public/courses/llm-agents/minigpt.json): each context is\n"
        " * encoded with bpe-merges.json, run through `adelante`, and the logits of its LAST\n"
        " * position kept, rounded to 4 decimals like the weights. Do not edit by hand; re-run it.\n"
        " *\n"
        " * `labels` spells the %d most probable entries (the rows the widget draws); the rest of\n"
        " * the 512 are drawn as one aggregated row. math/__tests__/sampling.test.ts checks the\n"
        " * labels against the merge table and the probabilities against the numbers the lesson's\n"
        " * first cell prints from Pyodide.\n"
        " */\n\n"
        "export interface SamplingPreset {\n"
        "  /** Locale-invariant state key. */\n"
        '  readonly id: "open" | "peaked";\n'
        "  /** The prompt, as the model read it. Spanish-bound: the checkpoint is (corpora.ts). */\n"
        "  readonly context: string;\n"
        "  /** Entry id → its text, for the most probable entries only. */\n"
        "  readonly labels: Readonly<Record<number, string>>;\n"
        "  /** The 512 logits of the last position, in id order. */\n"
        "  readonly logits: readonly number[];\n"
        "}\n\n"
        "export const SAMPLING_PRESETS: readonly SamplingPreset[] = [\n%s\n];\n"
    ) % (N_ETIQUETAS, "\n".join(bloques))
    with open(args.salida, "w", encoding="utf-8") as f:
        f.write(ts)
    print("escrito", os.path.relpath(args.salida, RAIZ))


if __name__ == "__main__":
    main()
